#listen on https
server {
  listen 443 ssl;
  server_name localhost
  server;
  ssl_certificate /path/to/server.crt;
  ssl_certificate_key /path/to/server.key;

  location / {
    proxy_pass http://<ip_address>:<port>;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}

#listen on http- redirect to https
server {
  listen 80;
  server_name localhost;

  return 301 https://$host$request_uri
}
