worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  sendfile on;
  keepalive_timeout 65;

  #logging(modify paths giving some sample paths)
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  #load balancer
  upstream backend_servers {
    # this is algorithm(least connections get requests) for distributing load, modify if needed
    least_conn;

    #modify to ip addresses of machines together with port numbers
    server 127.0.0.1:5000 max_fails=3 fail_timeout=10s;
    server 127.0.0.1:5001 max_fails=3 fail_timeout=10s;
    server 127.0.0.1:5002 max_fails=3 fail_timeout=10s;
  }

  #redirect HTTP -> HTTPS
  server {
    listen 80;
    server_name your-domain.com;

    return 301 https://$host$request_uri;
  }

  #HTTPS Server (main entry)
  server {
    listen 443 ssl http2;
    server_name your-domain.com;

    #SSL certificates- change paths accordingly giving some sample ones
    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    #Strong SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    #Security Headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1;mode=block";

    #Gzip compression
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    #Main API route( load balanced)
    location / {
      proxy_pass http://backend_servers;

      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;

      proxy_connect_timeout 5s;
      proxy_read_timeout 30s;
    }

    location /auth/ {
      proxy_pass http://127.0.0.1:7000;
    }

    #Health check endpoint
    location /health {
      return 200 "OK"
    }
  }
}
  
